# Generated by Django 5.2.6 on 2025-10-07 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_update_categoria_updatedat_estatu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('nombre_temporal', models.CharField(max_length=255)),
                ('ruta', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=100)),
                ('tamano', models.IntegerField()),
                ('descripcion_corta', models.CharField(blank=True, max_length=150, null=True)),
                ('descripcion_larga', models.TextField(blank=True, null=True)),
                ('descargas', models.IntegerField()),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(blank=True, null=True)),
                ('fk_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Archivo',
                'db_table': 'archivo',
                'managed': True,
            },
        ),
    ]
