# Generated by Django 5.2.6 on 2025-10-07 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_archivo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('resumen', models.CharField(blank=True, max_length=255, null=True)),
                ('contenido', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('vistas', models.IntegerField(blank=True, null=True)),
                ('fk_categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.categoria')),
                ('fk_estatu', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.estatu')),
                ('fk_foto_portada', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.archivo')),
                ('fk_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Publicacion',
                'db_table': 'publicacion',
                'managed': True,
            },
        ),
    ]
