# Generated by Django 5.2.6 on 2025-10-13 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_publicacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicacionArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('fk_archivo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.archivo')),
                ('fk_publicacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.publicacion')),
                ('fk_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Publicacion_archivo',
                'db_table': 'publicacion_archivo',
                'managed': True,
                'unique_together': {('fk_publicacion', 'fk_archivo')},
            },
        ),
    ]
